project:
  type: book
  
lang: de

book:
  title: "Test"
  author: "Johannes Feldhege"
  output-dir: "docs"
  output-file: "book"
  chapters:
    - index.qmd
    - chapter_1.qmd

format:
  pdf:
    documentclass: scrbook
    
    toc: true
    toc-depth: 3
    
    papersize: A4
    linestretch: 1.25
    fontsize: 11pt
    indent: false
