on:
  push:
    branches: main

name: Render

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
